source "https://rubygems.org"

ruby "2.3.1"

gem "sinatra"
gem "activerecord"
gem "sinatra-activerecord"
gem "pg", "~> 0.15"
gem "rerun"
gem "rake", "~> 10.4.2"
gem "json", "~> 1.8.3"
gem "bcrypt", "~> 3.1.11"
gem "sinatra-flash", "~> 0.3.0"
gem "minitest"
gem "rack-test"